### ISSUE TITLE
Allow to delete / restart stuck generations

### ISSUE THREAD

**Issue by anbraten** [zernonia/vue0#15]
Sometime a generation fails (see https://www.vue0.dev/t/xdnyiqmc31a2). Therefore it would be nice to restart a generation or allow to simply delete it.

**Comment by zernonia** [comment]
currently we have delete version/delete generation

**Comment by anbraten** [comment]
In this case I can not delete it as its still running, so maybe that check needs to be removed.

**Comment by zernonia** [comment]
If the generation stuck after 5 minutes, it can be regenerate with a new button added (only shown when stucked). Also allow deletion of generation/version when it is running
