### ISSUE TITLE
Continuous loading screen once started generation

### ISSUE THREAD

**Issue by roobr** [zernonia/vue0#16]
Continuous loading screen once started generation
![image](https://github.com/zernonia/vue0/assets/9066749/f7f0f8c3-43a8-483f-98be-4c001dfcfe16)

**Comment by wssnail** [comment]
I also encountered the same situation

**Comment by zernonia** [comment]
Yo guys.. thanks for the issue. I'm added a better error catching logic. Now if it's related to API error will be shown 😁
