### ISSUE TITLE
open ai key missing 

### ISSUE THREAD

**Issue by Masumrahmanhasan** [zernonia/vue0#7]
when try to search anything it gives missing open ai key 
<img width="688" alt="Screenshot 2024-01-06 at 7 30 33 PM" src="https://github.com/zernonia/vue0/assets/55694939/47a3701d-5f52-4249-a6dc-01e620b7041e">

**Comment by anbraten** [comment]
You have to login using github first (at the top right corner) and enter your api key by clicking your user icon.

**Comment by PMLS3** [comment]
What should the callback URL be?

**Comment by zernonia** [comment]
@Masumrahmanhasan  yup. It's use your own key tools.. where you need to login and use your own openai key.. by following the steps mentioned by @anbraten .


@PMLS3  what do you mean yaaa?

**Comment by PMLS3** [comment]
@zernonia sorry for not being clear, I downloaded the repo and want to run it locally. So I have setup my github tokens and was just wondering for the callback url where should it point too.

**Comment by anbraten** [comment]
Its: https://www.vue0.dev/api/auth/github
